version: '3'
services:

# Nginx Service
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../public:/var/www/public
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php
    environment: 
      - TZ=Europe/Kyiv
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

# Certbot Service
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/logs/:/var/log/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    environment: 
      - TZ=Europe/Kyiv
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# PHP 8
  php:
    build:
      context: ./php
      dockerfile: php/Dockerfile
    volumes:
      - .:/var/www
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
    restart: unless-stopped
    environment: 
      - TZ=Europe/Kyiv

# Mysql 8
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      TZ: "Europe/Kyiv"
    volumes:
      - "mysql_data:/var/lib/mysql"

# PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    # Links the PHPMyAdmin service to the MySQL database service
      - mysql 
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
  mysql_data: { driver: local }
